name: SBOM Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM
        run: syft dir:. -o json > sbom.json

      - name: Patch SBOM with name and version
        run: |
          python3 - <<EOF
          import json
          with open("sbom.json") as f:
              sbom = json.load(f)
          sbom["artifactName"] = "sbom-octopus-test"
          sbom["artifactVersion"] = "0.0.1"
          with open("sbom.json", "w") as f:
              json.dump(sbom, f, indent=2)
          EOF

      - name: Store SBOM in repo
        run: |
          mkdir -p reports
          cp sbom.json reports/sbom.json
          git config user.name "github-actions[bot]"
