name: Generate SBOM

on:
  push:
    branches:
      - main   # ✅ trigger only on pushes to main

jobs:
  sbom:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: 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

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh \
          | sh -s -- -b /usr/local/bin

      - name: Generate SBOM
        run: syft dir:. -o json > sbom.json

      - name: Save SBOM to reports/
        run: |
          mkdir -p reports
          cp sbom.json reports/sbom.json

      - name: Commit and Push SBOM
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add reports/sbom.json
          git commit -m "Add SBOM report [skip ci]" || echo "No changes to commit"
          git push https://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@github.com/PrathapHS/SBOM-Octopus.git HEAD:main
