name: Generate and Upload SBOM

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # allows manual trigger

jobs:
  sbom:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Install Syft
      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
          syft version

      # 3. Generate SBOM
      - name: Generate SBOM
        run: |
          syft dir:. -o json --name sbom-octopus-test --version 0.0.1 > sbom.json

      # 4. Show files
      - name: Show files
        run: ls -la

      # 5. Upload sbom.json as GitHub Artifact
      - name: Upload sbom.json as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json

      # 6. Upload SBOM to Octopus
      - name: Upload SBOM to Octopus
        env:
          OCTOPUS_SERVER: ${{ secrets.OCTOPUS_SERVER }}
          OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
          OCTOPUS_PROJECT_ID: ${{ secrets.OCTOPUS_PROJECT_ID }}
        run: |
          curl -X POST "${OCTOPUS_SERVER}/api/artifacts?overwriteMode=OverwriteExisting" \
            -H "X-Octopus-ApiKey: ${OCTOPUS_API_KEY}" \
            -F "file=@sbom.json" \
            -F "project=${OCTOPUS_PROJECT_ID}" \
            -F "name=sbom.json"
